---
version: '3.7'
services:
  db:
    image: postgres:10.12
    container_name: roi_calc_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      bc-dev-backend:
        aliases:
          - bc-dev-database
networks:
  bc-dev-backend:
    driver: bridge
    name: bc-dev-backend
